apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-webapp123
  labels:
    hr: web
spec:
  replicas: 2
  selector:
    matchLabels:
      hr: web
  template:
    metadata:
      labels:
        hr: web
    spec:
      containers:
      - name: kode
        image: kodekloud/webapp-color
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hr-web-svc123
spec:
  type: NodePort
  selector:
    hr: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8083
