apiVersion: v1
kind: Pod
metadata:
  name: multipod
  labels:
    app: nginx 
spec:
  containers:
  - name: alpha
    image: nginx
    env:
    - name: name
      value: alpha
    ports:
    - containerPort: 80
  
  - image: busybox
    env:
    - name: name
      value: beta
    command:
      - sleep
      - "3600"
    imagePullPolicy: Always
    name: beta
  restartPolicy: Always
