apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-123
  labels:
    app: nginx
spec:
  replicas: 30
  selector:
    matchLabels:
      app: nginx     
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
        - name: nginx
          image: sharanushettar/client
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  type: NodePort
  selector:
    app: nginx 
  ports:
  - port: 80
    targetPort: 8081
